services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: url_shortener_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: url-shortener
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/url_shortener_db
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_BASE_URL: http://localhost:8080

volumes:
  mysql_data:
