# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE (Railway MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://${mysql.railway.internal}:${3306}/${railway}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${root}
spring.datasource.password=${cOowvOprRYWmRQWnETLaqMhhOMClPyUp}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ===============================
# APP CONFIG
# ===============================
app.base-url=${APP_BASE_URL}
app.url.expiry-days=30
